#version: '3.8'
services:
  
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: integration
      MYSQL_DATABASE: integration_db
      MYSQL_USER: integration
      MYSQL_PASSWORD: integration
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
  #      - ./db/:/docker-entrypoint-initdb.dcd do ch

  api:
    build: .
    env_file:
      - .env
    ports:
      - "1997:1997"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      USER_PRINCIPAL: admin@admin.com
      USER_PASSWORD: password123
      SERVER_PORT: 1997
      SPRING_PROFILES_ACTIVE: native-test
      API_PREFIX: "api/v1/"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/integration_db
      SPRING_DATASOURCE_USERNAME: integration
      SPRING_DATASOURCE_PASSWORD: integration
      SARRE_USD_TO_CENT: 100
      SARRE_NGN_TO_KOBO: 0.37
      PAYSTACK_PUB_KEY: ${PAYSTACK_PUB_KEY}
      PAYSTACK_SECRET_KEY: ${PAYSTACK_SECRET_KEY}
      CORS_UI_DOMAIN: http://localhost:4200/
      AWS_BUCKET: my-bucket
      AWS_ACCESS_KEY_ID: access-id
      AWS_SECRET_ACCESS_KEY: secret-id
      AWS_PAYSTACK_SECRET_ID: secrete-id
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1997/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  db-data: {}