version: '3.9'
services:

#  api:
#    container_name: api
#    image: "emmanuelu17/sara-brand-server:latest"
#    ports:
#      - "1997:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy
#    environment:
#      SERVER_PORT: 8080
#      SPRING_PROFILES_ACTIVE: dev
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sara_brand_db
#      SPRING_DATASOURCE_USERNAME: sara
#      SPRING_DATASOURCE_PASSWORD: sara
#      AWS_ACCESS_KEY_ID:
#      AWS_SECRET_ACCESS_KEY:

  mysql:
    image: "mysql:latest"
    container_name: mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sara
      MYSQL_DATABASE: sara_brand_db
      MYSQL_USER: sara
      MYSQL_PASSWORD: sara
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}
