version = 0.1
[default.deploy.parameters]
stack_name = "sara-brand-app"
resolve_s3 = true
s3_prefix = "sara-brand-app"
region = "ca-central-1"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
