name: Sarre Brand API
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK Temurin
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: mvn -Pnative spring-boot:build-image -DskipTests

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Push Image to Docker Hub
        run: docker push --all-tags emmanuelu17/sara-brand-server