name: Capstone Server
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-native-image:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 'graalvm'

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          mvn clean install -DskipTests
          cd webserver/
          mvn spring-boot:build-image -Pnative -DskipTests

      - name: Push image to dockerhub
        run: |
          docker image tag webserver-native:latest emmanuelu17/capstone-api:latest
          docker push --all-tags emmanuelu17/capstone-api