name: Sarre Brand API Actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-native-image:
    name: Build and Deploy native image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build native image
        run: docker build --tag capstone-server:latest . --progress=plain

      - name: Push native image to dockerhub
        run: |
          docker image tag capstone-server:latest emmanuelu17/capstone-native:latest
          docker push --all-tags emmanuelu17/capstone-native