name: Capstone Server
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-native-image:
    name: Build and Deploy native image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build native image
        run: |
          mvn clean install -DskipTests
          docker build --tag capstone-server:latest . --progress=plain

      - name: Push native image to dockerhub
        run: |
          docker image tag capstone-server:latest emmanuelu17/capstone-server:latest
          docker push --all-tags emmanuelu17/capstone-server
