name: Capstone Api deploy
on:
  pull_request:
    branches:
      - master

jobs:
  deploy-native-image:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK Graal
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Log into DockerHub
        uses: docker/login-action@v3
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Maven install
        run: mvn clean install -DskipTests

      - name: Build Native Image
        run: docker build --tag capstone-api:latest . --progress=plain

      - name: Push image to dockerhub
        run: |
          docker image tag capstone-api:latest emmanuelu17/capstone-api:latest
          docker push --all-tags emmanuelu17/capstone-api