name: Sara Brand Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Master Branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Checkout master
        uses: actions/checkout@v3
        with:
          submodules: true

      # Log into dockerhub
      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          #!/usr/bin/env bash
          
          # chmod grants permission to run mvnw
          chmod +x mvnw
          ./mvnw clean spring-boot:build-image -DskipTests
        shell: bash

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Push image to Docker Hub
        run: docker push --all-tags emmanuelu17/sara-brand-server
          
