name: Sara Brand Server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy to docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Checkout master
        uses: actions/checkout@v3
        with:
          submodules: true

      # Log into DockerHub
      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: emmanuelu17
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Clean package
      - name: Clean package
        run: ./mvn clean

      # Build image
      - name: Build Image
        run: ./mvnw clean spring-boot:build-image

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      # Deploy image to docker registry
      - name: Push Image to Docker Hub
        run: docker push --all-tags emmanuelu17/sara-brand-server