name: Run tests before merging into master
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Development Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up JDK Temurin
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run tests
        run: |
          #!/usr/bin/env bash
          # chmod grants permission to run mvnw
          chmod +x mvnw
          ./mvnw clean
          ./mvnw test
        shell: bash