name: Run tests before merging into master
on:
  push:
    branches:
      - dev

jobs:
  TDD-test:
    name: TDD tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Maven install
        run: mvn clean install -DskipTests

      - name: Run tests
        run: |
          cd webserver/
          mvn test -DCI_PROFILE=true -DPAYSTACK_PUB_KEY=PAYSTACK_PUB_KEY -DPAYSTACK_SECRET_KEY=PAYSTACK_SECRET_KEY
        shell: bash
        env:
          PAYSTACK_PUB_KEY: ${{ secrets.PAYSTACK_PUB_KEY }}
          PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}

  native-image-test:
    name: Native image test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Maven install
        run: mvn clean install -DskipTests

      - name: Build Native Image
        run: docker build --tag capstone-api:latest . --progress=plain

      - name: Test against native image
        run: |
          export PAYSTACK_PUB_KEY=${{ secrets.PAYSTACK_PUB_KEY }}
          export PAYSTACK_SECRET_KEY=${{ secrets.PAYSTACK_SECRET_KEY }}
          cd integration/
          mvn test -DNATIVE_CI_PROFILE=true