name: Run tests before merging into master
on:
  push:
    branches:
      - dev

jobs:
  TDD-test:
    name: TDD tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run tests
        run: |
          mvn clean install -DskipTests
          cd webserver/
          mvn test -DPAYSTACK_PUB_KEY=PAYSTACK_PUB_KEY -DPAYSTACK_SECRET_KEY=PAYSTACK_SECRET_KEY
        shell: bash
        env:
          PAYSTACK_PUB_KEY: ${{ secrets.PAYSTACK_PUB_KEY }}
          PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}

  native-image-test:
    name: Native image test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set env variables
        run: |
          touch .env
          echo PAYSTACK_PUB_KEY=$PAYSTACK_PUB_KEY >> .env
          echo PAYSTACK_SECRET_KEY=$PAYSTACK_SECRET_KEY >> .env
          echo AWS_BUCKET=$AWS_BUCKET >> .env
          echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> .env
          echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> .env
        shell: bash
        env:
          PAYSTACK_PUB_KEY: ${{ secrets.PAYSTACK_PUB_KEY }}
          PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build native image
        run: |
          mvn clean install -DskipTests
          cd webserver/
          mvn spring-boot:build-image -Pnative -DskipTests

      - name: Compose up
        run: |
          cd ..
          docker compose up -d

      - name: Run tests
        run: |
          cd integration
          mvn test

      - name: Compose down
        run: |
          cd ..
          docker compose down -v