name: Run tests before merging into master
on:
  push:
    branches:
      - dev

jobs:
  TDD-test:
    name: TDD tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run tests
        run: |
          mvn clean install -DskipTests
          cd webserver/
          mvn test

  native-image-test:
    name: Native image test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run tests
        run: |
          mvn clean install -DskipTests
          cd integration/
          mvn test